datasets:
  vqarad:
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      ann_path: /ibex/user/sabbam0a/grad/MiniGPT-4/medvqa_dataset/RAD/annotations_train_w_captions_medicap.json
      image_path: /ibex/user/sabbam0a/grad/MiniGPT-4/medvqa_dataset/RAD/images
